#!/usr/bin/env python3
"""Compare Quarto Markdown while ignoring runtime-generated widget IDs."""

from __future__ import annotations

import difflib
import re
import sys
from pathlib import Path


def normalize_markdown(markdown: str) -> str:
    """Remove known non-semantic IDs generated by htmlwidgets."""
    markdown = re.sub(r"htmlwidget-[0-9a-f]+", "htmlwidget-ID", markdown)
    return re.sub(r'"[0-9a-f]{8,32}"', '"DATA-ID"', markdown)


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: compare-quarto-output.py EXPECTED ACTUAL", file=sys.stderr)
        return 2

    expected_path, actual_path = map(Path, sys.argv[1:])
    expected = normalize_markdown(expected_path.read_text(encoding="utf-8"))
    actual = normalize_markdown(actual_path.read_text(encoding="utf-8"))

    if expected == actual:
        return 0

    diff = difflib.unified_diff(
        expected.splitlines(),
        actual.splitlines(),
        fromfile=str(expected_path),
        tofile=str(actual_path),
        n=3,
    )
    print("\n".join(list(diff)[:80]), file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
